apiVersion: v1
kind: Service
metadata:
  name: webapp-application-service
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: my-app
